name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests (web package)
        working-directory: ./packages/web
        run: npm run test:run

      - name: TypeScript type checking
        working-directory: ./packages/web
        run: npm run typecheck

      - name: Build web package
        working-directory: ./packages/web
        run: npm run build

  test-core:
    name: Test Core Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # Add core package tests when ready
      # - name: Run tests (core package)
      #   working-directory: ./packages/core
      #   run: npm test
