name: Deploy to Beta

on:
  workflow_dispatch:  # Manual trigger only
    inputs:
      branch:
        description: 'Branch to deploy to beta'
        required: true
        default: 'main'

jobs:
  test:
    name: Run Tests First
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        working-directory: ./packages/web
        run: npm run test:run

      - name: TypeScript type checking
        working-directory: ./packages/web
        run: npm run typecheck

  deploy:
    name: Deploy to Beta
    needs: test  # Only deploy if tests pass
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build (beta mode)
        working-directory: ./packages/web
        run: npm run build:beta

      - name: Add CNAME
        working-directory: ./packages/web
        run: echo audio-analyzer.tinytech.site > dist/CNAME

      - name: Deploy to GitHub Pages (beta path)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/web/dist
          destination_dir: beta
          force_orphan: false
