name: CI - Main Branch

# NOTE: Deployment now handled by Cloudflare Pages
# This workflow only runs tests to ensure code quality before Cloudflare deploys

on:
  push:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: |
          # Workaround for npm ci platform-specific dependency issues
          # See: https://github.com/npm/cli/issues/4828
          # Remove lockfile and use npm install to handle optional deps correctly
          rm -f package-lock.json
          npm install --no-audit

      - name: Run tests
        working-directory: ./packages/web
        run: npm run test:run

      - name: TypeScript type checking
        working-directory: ./packages/web
        run: npm run typecheck
